baseURL = "https://wztj.893810.xyz/"
title = "SR 极速影院 - 豆瓣新片速览"
theme = "hugo-theme-stack"
languageCode = "zh-cn"

# 全局作者信息
[author]
  name = "luxingzhen"

[params]
  EnableAlgolia = false
  mainSections = ["posts"]
  author = "luxingzhen"
  description = "最新豆瓣高分电影/剧集介绍，一键跳转观看平台"
  env = "production"
  
  # 1. 解决图片防盗链的核心
  header_custom = ['<meta name="referrer" content="no-referrer">']
  
  # 2. 界面功能设置
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  
  # 3. 首页欢迎语
  [params.homeInfoParams]
    Title = "欢迎来到我的站点"
    Content = "自动更新豆瓣热门视频介绍！"

  # 4. 资源处理
  [params.assets]
    disableHLJS = false

# 5. 渲染设置：允许 HTML 嵌入（非常重要）
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS"]

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"# Trigger Deploy

[[menu.main]]
  identifier = "now-playing"
  name = "热映"
  url = "/tags/热映/"
  weight = 10

[[menu.main]]
  identifier = "coming-soon"
  name = "即将上映"
  url = "/tags/即将上映/"
  weight = 20

[[menu.main]]
  identifier = "high-score"
  name = "高分推荐"
  url = "/tags/高分推荐/"
  weight = 30
